name: Terraform Deploy

on:
  push:
    branches:
      - 'dev'
      - 'staging'
      - 'prod'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployments  # Adjust if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0  # Specify your version

      - name: Terraform Init
        run: terraform init -backend-config="path/to/remote/state"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="terraform.tfvars.${{ github.ref_name }}"

      - name: Terraform Apply
        if: github.ref_name != 'prod'
        run: terraform apply -auto-approve -var-file="terraform.tfvars.${{ github.ref_name }}"

      # For prod environment: manual approval
      - name: Terraform Apply to Production
        if: github.ref_name == 'prod'
        run: terraform apply -var-file="terraform.tfvars.prod"
        env:
          TF_VAR_approval: ${{ github.event.workflow_dispatch.inputs.approval }}
